# Base information
baseURL = "https://alvaroalbero-portfolio.netlify.app/"
languageCode = "en-gb"
title = "Alvaro Albero"
theme = "hugo-developer-portfolio"
googleAnalytics = ""
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=2
  
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight=3


[params]
home = "Home"
# Meta data
description = "The website of Alvaro Albero, Software Engineer with a MS in Computer Science from George Washington University"
author = "Alvaro Albero"


  [params.contact]
  enable = true
  formAction = "" #contact form works with formspree.io

  [params.footer]
  email = "aalbero@gwu.edu"
  address = "Silver Spring, MD"
  googlemaps = "https://www.google.com/maps/place/Silver+Spring,+MD/@39.0086876,-77.0878844,12z/data=!3m1!4b1!4m5!3m4!1s0x89b7cf4e666ae927:0x8433a865b29adf!8m2!3d38.9906657!4d-77.026088"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

